apiVersion: v1
kind: Pod
metadata:
  labels:
    run: kafka-consumer
  name: kafka-consumer
  namespace: kafka
spec:
  containers:
    - args:
        - bin/kafka-console-consumer.sh
        - --bootstrap-server
        - my-cluster-kafka-bootstrap:9092
        - --topic
        - my-topic
        - --from-beginning
      image: quay.io/strimzi/kafka:0.24.0-kafka-2.8.0
      name: kafka-consumer
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-g9p9t
          readOnly: true
  restartPolicy: Never
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - name: kube-api-access-g9p9t
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
                - key: ca.crt
                  path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
                - fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
                  path: namespace
