apiVersion: v1
kind: Pod
metadata:
  labels:
    run: kafka-producer-activities
    type: kafka-producer
  name: kafka-producer-activities
  namespace: kafka
spec:
  containers:
    - args:
        - bin/kafka-console-producer.sh
        - --broker-list
        - my-cluster-kafka-bootstrap:9092
        - --topic
        - activities-topic
      image: quay.io/strimzi/kafka:0.24.0-kafka-2.8.0
      name: kafka-producer-activities
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: kafka-producer-expenses
    type: kafka-producer
  name: kafka-producer-expenses
  namespace: kafka
spec:
  containers:
    - args:
        - bin/kafka-console-producer.sh
        - --broker-list
        - my-cluster-kafka-bootstrap:9092
        - --topic
        - expenses-topic
      image: quay.io/strimzi/kafka:0.24.0-kafka-2.8.0
      name: kafka-producer-expenses
  restartPolicy: Never