apiVersion: v1
kind: Service
metadata:
  labels:
    app: xpenses-quarkus-deploy
  name: xpenses-quarkus-deploy
  namespace: kafka
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: xpenses-quarkus-deploy
  type: NodePort