apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xpenses-quarkus-deploy
  name: xpenses-quarkus-deploy
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xpenses-quarkus-deploy
  template:
    metadata:
      labels:
        app: xpenses-quarkus-deploy
    spec:
      containers:
      - image: xpenses-quarkus
        name: xpenses-quarkus
        imagePullPolicy: Never